export const SET_CURRENT_AUTH = 'SET_CURRENT_AUTH';

export const ADD_INDICATOR = 'ADD_INDICATOR',
  REMOVE_INDICATOR = 'REMOVE_INDICATOR';

export const ADD_REPO = 'ADD_REPO',
  LOAD_REPO_LIST = 'LOAD_REPO_LIST',
  REMOVE_REPO = 'REMOVE_REPO',
  UPDATE_REPO = 'UPDATE_REPO';

export const ADD_BUILD = 'ADD_BUILD',
  LOAD_BUILD_LIST = 'LOAD_BUILD_LIST',
  PRE_LOAD_BUILD_LIST = 'PRE_LOAD_BUILD_LIST',
  REMOVE_BUILD = 'REMOVE_BUILD',
  UPDATE_BUILD = 'UPDATE_BUILD';
