apiVersion: v1
kind: Service
metadata:
  name: vcs-server
  namespace: default
  labels:
    app: vcs-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: vcs-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vcs-server
  namespace: default
  labels:
    app: vcs-server
spec:
  selector:
    matchLabels:
      app: vcs-server
  serviceName: vcs-server
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 2
    #   maxUnavailable: 1
  # minReadySeconds: 5
  # revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: vcs-server
    spec:
      containers:
        - name: zeus
          image: gcr.io/zeus-176020/zeus:latest
          imagePullPolicy: Always
          args: ['zeus', 'vcs-server', '--host=0.0.0.0', '--port=8080']
          env:
            - name: GC_PROJECT
              value: zeus-176020
            - name: GCS_BUCKET
              value: 'artifacts.zeus-176020.appspot.com'
            - name: DB_HOST
              value: pgbouncer
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zeus
                  key: secret-key
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-secret
            - name: DOMAIN
              value: zeus.ci
            - name: GET_HOSTS_FROM
              value: env
            - name: REPO_ROOT
              value: '/tmp/repo-cache'
            - name: MAIL_SERVER
              value: 'smtp.mailgun.org'
            - name: MAIL_PORT
              value: '2525'
            - name: MAIL_USE_TLS
              value: '1'
            - name: MAIL_USE_SSL
              value: '0'
            - name: MAIL_USERNAME
              value: 'postmaster@mg.zeus.ci'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: password
            - name: MAIL_DEFAULT_SENDER
              value: 'Zeus <noreply@mg.zeus.ci>'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: '/var/run/secret/cloud.google.com/service-account.json'
            - name: ALLOWED_ORIGINS
              value: 'updates.zeus.ci,zeus.ci'
            - name: PUBSUB_ENDPOINT
              value: 'https://updates.zeus.ci'
            - name: VCS_SERVER_ENDPOINT
              value: 'http://vcs-server'
            - name: ROLE
              value: vcs-server
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: queue
                  key: broker_url
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
          volumeMounts:
            - name: repo-cache
              mountPath: '/tmp/repo-cache'
            - name: 'service-account'
              mountPath: '/var/run/secret/cloud.google.com'
          resources:
            requests:
              cpu: 1200m
              memory: 1500Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
      volumes:
        - name: service-account
          secret:
            secretName: 'zeus-service-account'
  volumeClaimTemplates:
    - metadata:
        name: repo-cache
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5000Gi
