apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: zeus
        image: gcr.io/zeus-176020/zeus:latest
        imagePullPolicy: Always
        args: ["zeus", "web", "--host=0.0.0.0", "--port=8080"]
        env:
        - name: GC_PROJECT
          value: zeus-176020
        - name: GCS_BUCKET
          value: 'artifacts.zeus-176020.appspot.com'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: SENTRY_DSN_FRONTEND
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn-frontend
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: zeus
              key: secret-key
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github
              key: client-secret
        - name: DOMAIN
          value: zeus.ci
        - name: SSL
          value: 'true'
        - name: GET_HOSTS_FROM
          value: env
        - name: REPO_ROOT
          value: '/mnt/repo-cache'
        - name: MAIL_SERVER
          value: 'smtp.mailgun.org'
        - name: MAIL_PORT
          value: '2525'
        - name: MAIL_USE_TLS
          value: '1'
        - name: MAIL_USE_SSL
          value: '0'
        - name: MAIL_USERNAME
          value: 'postmaster@mg.zeus.ci'
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail
              key: password
        - name: MAIL_DEFAULT_SENDER
          value: 'noreply@mg.zeus.ci'
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: '/var/run/secret/cloud.google.com/service-account.json'
        - name: ALLOWED_ORIGINS
          value: 'updates.zeus.ci,zeus.ci'
        - name: PUBSUB_ENDPOINT
          value: 'https://updates.zeus.ci'
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: queue
              key: broker_url
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
        volumeMounts:
          - name: nfs
            mountPath: "/mnt/repo-cache"
          - name: "service-account"
            mountPath: "/var/run/secret/cloud.google.com"
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=zeus-176020:us-central1:zeus-prod-06947e6=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: service-account
          secret:
            secretName: "zeus-service-account"
