apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: zeus-ci
  namespace: default
  labels:
    app: web
spec:
  domains:
    - zeus.ci
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-gce
  namespace: default
  labels:
    app: web
  annotations:
    kubernetes.io/ingress.global-static-ip-name: zeus-ci
    networking.gke.io/managed-certificates: zeus-ci
spec:
  backend:
    serviceName: web
    servicePort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 6
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: zeus
          image: gcr.io/zeus-176020/zeus:latest
          imagePullPolicy: Always
          args: ['zeus', 'web', '--host=0.0.0.0', '--port=8080']
          env:
            - name: GC_PROJECT
              value: zeus-176020
            - name: GCS_BUCKET
              value: 'artifacts.zeus-176020.appspot.com'
            - name: DB_HOST
              value: pgbouncer
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: SENTRY_DSN_FRONTEND
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn-frontend
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zeus
                  key: secret-key
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-secret
            - name: DOMAIN
              value: zeus.ci
            - name: SSL
              value: 'true'
            - name: GET_HOSTS_FROM
              value: env
            - name: REPO_ROOT
              value: '/tmp/repo-cache'
            - name: MAIL_SERVER
              value: 'smtp.mailgun.org'
            - name: MAIL_PORT
              value: '2525'
            - name: MAIL_USE_TLS
              value: '1'
            - name: MAIL_USE_SSL
              value: '0'
            - name: MAIL_USERNAME
              value: 'postmaster@mg.zeus.ci'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: password
            - name: MAIL_DEFAULT_SENDER
              value: 'Zeus <noreply@mg.zeus.ci>'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: '/var/run/secret/cloud.google.com/service-account.json'
            - name: ALLOWED_ORIGINS
              value: 'updates.zeus.ci,zeus.ci'
            - name: PUBSUB_ENDPOINT
              value: 'https://updates.zeus.ci'
            - name: VCS_SERVER_ENDPOINT
              value: 'http://vcs-server'
            - name: ROLE
              value: web
            - name: RABBITMQ_HOST
              value: 'rabbitmq-1-rabbitmq-svc.default.svc.cluster.local'
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_USER
              value: rabbit
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
          volumeMounts:
            - name: 'service-account'
              mountPath: '/var/run/secret/cloud.google.com'
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 1000m
              memory: 600Mi
      volumes:
        - name: service-account
          secret:
            secretName: 'zeus-service-account'
