apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6
      maxUnavailable: 2
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: zeus
          image: gcr.io/zeus-176020/zeus:latest
          imagePullPolicy: Always
          args: ['zeus', 'worker', '--cron']
          env:
            - name: GC_PROJECT
              value: zeus-176020
            - name: GCS_BUCKET
              value: 'artifacts.zeus-176020.appspot.com'
            - name: DB_HOST
              value: pgbouncer
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zeus
                  key: secret-key
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-secret
            - name: DOMAIN
              value: zeus.ci
            - name: GET_HOSTS_FROM
              value: env
            - name: REPO_ROOT
              value: '/tmp/repo-cache'
            - name: MAIL_SERVER
              value: 'smtp.mailgun.org'
            - name: MAIL_PORT
              value: '2525'
            - name: MAIL_USE_TLS
              value: '1'
            - name: MAIL_USE_SSL
              value: '0'
            - name: MAIL_USERNAME
              value: 'postmaster@mg.zeus.ci'
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail
                  key: password
            - name: MAIL_DEFAULT_SENDER
              value: 'Zeus <noreply@mg.zeus.ci>'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: '/var/run/secret/cloud.google.com/service-account.json'
            - name: ALLOWED_ORIGINS
              value: 'updates.zeus.ci,zeus.ci'
            - name: PUBSUB_ENDPOINT
              value: 'https://updates.zeus.ci'
            - name: VCS_SERVER_ENDPOINT
              value: 'http://vcs-server'
            - name: ROLE
              value: worker
            - name: RABBITMQ_HOST
              value: 'rabbitmq-1-rabbitmq-discovery.default.svc.cluster.local'
            - name: RABBITMQ_PORT
              value: '5672'
            - name: RABBITMQ_USER
              value: rabbit
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-1-rabbitmq-secret
                  key: rabbitmq-pass
          readinessProbe:
            exec:
              command:
                - test
                - '`ps aux | grep "[z]eus worker"`'
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - test
                - '`ps aux | grep "[z]eus worker"`'
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: 'service-account'
              mountPath: '/var/run/secret/cloud.google.com'
          resources:
            requests:
              cpu: 1200m
              memory: 1500Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
      volumes:
        - name: service-account
          secret:
            secretName: 'zeus-service-account'
