"""cleanup_repo_access

Revision ID: 059fd6da96ee
Revises: e2f926a2b0fe
Create Date: 2018-12-19 11:31:47.040286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "059fd6da96ee"
down_revision = "e2f926a2b0fe"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_repository_access_repository_id", table_name="repository_access")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_repository_access_repository_id",
        "repository_access",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###
