"""optional_label

Revision ID: 070ac78ddbcb
Revises: 8536b0fcf0a2
Create Date: 2019-11-25 10:46:05.502420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "070ac78ddbcb"
down_revision = "8536b0fcf0a2"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("build", "label", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("build", "label", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
