"""refactor_bundlestats

Revision ID: 0e26830acd30
Revises: 89a8aa1c611c
Create Date: 2018-01-05 13:26:00.762058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import zeus

# revision identifiers, used by Alembic.
revision = '0e26830acd30'
down_revision = '89a8aa1c611c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_asset',
                    sa.Column('job_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('chunk_names', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('repository_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column('id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column(
                        'date_created',
                        sa.TIMESTAMP(
                            timezone=True),
                        server_default=sa.text('now()'),
                        nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['repository_id'], ['repository.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('job_id', 'name', name='unq_bundle_asset')
                    )
    op.create_index(
        op.f('ix_bundle_asset_repository_id'),
        'bundle_asset',
        ['repository_id'],
        unique=False)
    op.create_table('bundle_entrypoint',
                    sa.Column('job_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('repository_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column('id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column(
                        'date_created',
                        sa.TIMESTAMP(
                            timezone=True),
                        server_default=sa.text('now()'),
                        nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['repository_id'], ['repository.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('job_id', 'name', name='unq_bundle_entrypoint')
                    )
    op.create_index(
        op.f('ix_bundle_entrypoint_repository_id'),
        'bundle_entrypoint',
        ['repository_id'],
        unique=False)
    op.create_table('bundle_entrypoint_asset',
                    sa.Column('entrypoint_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.Column('asset_id', zeus.db.types.guid.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['asset_id'], ['bundle_asset.id'], ),
                    sa.ForeignKeyConstraint(['entrypoint_id'], ['bundle_entrypoint.id'], ),
                    sa.PrimaryKeyConstraint('entrypoint_id', 'asset_id')
                    )
    op.drop_table('webpack_entrypoint')
    op.drop_table('webpack_asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpack_asset',
                    sa.Column('job_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column(
                        'chunk_names',
                        postgresql.ARRAY(
                            sa.VARCHAR()),
                        autoincrement=False,
                        nullable=True),
                    sa.Column(
                        'repository_id',
                        postgresql.UUID(),
                        autoincrement=False,
                        nullable=False),
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column(
                        'date_created',
                        postgresql.TIMESTAMP(
                            timezone=True),
                        server_default=sa.text('now()'),
                        autoincrement=False,
                        nullable=False),
                    sa.ForeignKeyConstraint(
                        ['job_id'],
                        ['job.id'],
                        name='webpack_asset_job_id_fkey',
                        ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['repository_id'],
                        ['repository.id'],
                        name='webpack_asset_repository_id_fkey',
                        ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='webpack_asset_pkey'),
                    sa.UniqueConstraint('job_id', 'filename', name='unq_webpack_asset')
                    )
    op.create_table('webpack_entrypoint',
                    sa.Column('job_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column(
                        'asset_names',
                        postgresql.ARRAY(
                            sa.VARCHAR()),
                        autoincrement=False,
                        nullable=True),
                    sa.Column(
                        'repository_id',
                        postgresql.UUID(),
                        autoincrement=False,
                        nullable=False),
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column(
                        'date_created',
                        postgresql.TIMESTAMP(
                            timezone=True),
                        server_default=sa.text('now()'),
                        autoincrement=False,
                        nullable=False),
                    sa.ForeignKeyConstraint(
                        ['job_id'],
                        ['job.id'],
                        name='webpack_entrypoint_job_id_fkey',
                        ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['repository_id'],
                        ['repository.id'],
                        name='webpack_entrypoint_repository_id_fkey',
                        ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='webpack_entrypoint_pkey'),
                    sa.UniqueConstraint('job_id', 'name', name='unq_webpack_entrypoint')
                    )
    op.drop_table('bundle_entrypoint_asset')
    op.drop_index(op.f('ix_bundle_entrypoint_repository_id'), table_name='bundle_entrypoint')
    op.drop_table('bundle_entrypoint')
    op.drop_index(op.f('ix_bundle_asset_repository_id'), table_name='bundle_asset')
    op.drop_table('bundle_asset')
    # ### end Alembic commands ###
