"""add_pending_artifact

Revision ID: 0f81e9efc84a
Revises: 61a1763b9c8d
Create Date: 2019-10-24 15:13:36.705288

"""
import zeus.db.types
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f81e9efc84a"
down_revision = "61a1763b9c8d"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_artifact",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("external_job_id", sa.String(length=64), nullable=False),
        sa.Column("external_build_id", sa.String(length=64), nullable=False),
        sa.Column("hook_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("file", zeus.db.types.file.File(), nullable=False),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hook_id"], ["hook.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pending_artifact",
        "pending_artifact",
        ["repository_id", "provider", "external_job_id", "external_build_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_artifact_hook_id"),
        "pending_artifact",
        ["hook_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_artifact_repository_id"),
        "pending_artifact",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pending_artifact_repository_id"), table_name="pending_artifact"
    )
    op.drop_index(op.f("ix_pending_artifact_hook_id"), table_name="pending_artifact")
    op.drop_index("idx_pending_artifact", table_name="pending_artifact")
    op.drop_table("pending_artifact")
    # ### end Alembic commands ###
