"""add_testcase_created_index

Revision ID: 15d0e6fc9b97
Revises: a8bd86b031b4
Create Date: 2020-05-22 10:51:06.776263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15d0e6fc9b97"
down_revision = "a8bd86b031b4"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_testcase_repo_created",
        "testcase",
        ["repository_id", "hash", "date_created"],
        unique=False,
    )
    op.drop_index("idx_testcase_repo_hash", table_name="testcase")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_testcase_repo_hash",
        "testcase",
        ["repository_id", "hash", "result"],
        unique=False,
    )
    op.drop_index("idx_testcase_repo_created", table_name="testcase")
    # ### end Alembic commands ###
