"""scheduled_repo_updates

Revision ID: 1782e8a9f689
Revises: 0f81e9efc84a
Create Date: 2019-10-24 23:24:34.861892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1782e8a9f689"
down_revision = "0f81e9efc84a"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repository",
        sa.Column("next_update", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repository", "next_update")
    # ### end Alembic commands ###
