"""add_repo_role

Revision ID: 1cb2c54f3831
Revises: 8e598bda7fda
Create Date: 2018-01-20 19:13:11.060203

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = '1cb2c54f3831'
down_revision = '8e598bda7fda'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'api_token_repository_access',
        sa.Column(
            'permission',
            zeus.db.types.enum.Enum(),
            nullable=False))
    op.add_column(
        'repository_access',
        sa.Column(
            'permission',
            zeus.db.types.enum.Enum(),
            server_default='1',
            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository_access', 'permission')
    op.drop_column('api_token_repository_access', 'permission')
    # ### end Alembic commands ###
