"""repo_name

Revision ID: 255363dbe2b1
Revises: e2ce8e26135a
Create Date: 2017-07-08 16:04:24.882114

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '255363dbe2b1'
down_revision = 'e2ce8e26135a'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('name', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'repository', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repository', type_='unique')
    op.drop_column('repository', 'name')
    # ### end Alembic commands ###
