"""build_author

Revision ID: 2d439d428034
Revises: 504ca52963d9
Create Date: 2017-07-10 15:26:29.117008

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2d439d428034'
down_revision = '504ca52963d9'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('author_id', zeus.db.types.guid.GUID(), nullable=True))
    op.create_index(op.f('ix_build_author_id'), 'build', ['author_id'], unique=False)
    op.create_foreign_key(None, 'build', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'build', type_='foreignkey')
    op.drop_index(op.f('ix_build_author_id'), table_name='build')
    op.drop_column('build', 'author_id')
    # ### end Alembic commands ###
