"""optimize_origin_index

Revision ID: 33da83c61635
Revises: cd1324dcb6ba
Create Date: 2019-01-23 12:47:40.304286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33da83c61635"
down_revision = "cd1324dcb6ba"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_build_outcomes",
        "build",
        ["status", "result", "date_created"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_build_outcomes", table_name="build")
    # ### end Alembic commands ###
