"""artifacts

Revision ID: 361695ca454c
Revises: a1b148fec5e1
Create Date: 2017-07-04 13:51:27.826987

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '361695ca454c'
down_revision = 'a1b148fec5e1'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'itemstat',
        sa.Column('id', zeus.db.types.guid.GUID(), nullable=False),
        sa.Column('item_id', zeus.db.types.guid.GUID(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('value', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_id', 'name', name='unq_itemstat_name')
    )
    op.create_table(
        'artifact',
        sa.Column('id', zeus.db.types.guid.GUID(), nullable=False),
        sa.Column('job_id', zeus.db.types.guid.GUID(), nullable=False),
        sa.Column('testcase_id', zeus.db.types.guid.GUID(), nullable=True),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('type', zeus.db.types.enum.Enum(), server_default='0', nullable=False),
        sa.Column('file', zeus.db.types.file.File(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.Column('repository_id', zeus.db.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['testcase_id'], ['testcase.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_repository_id'), 'artifact', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_repository_id'), table_name='artifact')
    op.drop_table('artifact')
    op.drop_table('itemstat')
    # ### end Alembic commands ###
