"""fix_provider_constraints

Revision ID: 4235d2fae82a
Revises: b605b5627d91
Create Date: 2017-07-11 13:33:16.664322

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4235d2fae82a'
down_revision = 'b605b5627d91'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_build_provider', 'build', type_='unique')
    op.create_unique_constraint(
        'unq_build_provider', 'build', ['repository_id', 'provider', 'external_id']
    )
    op.drop_constraint('unq_job_provider', 'job', type_='unique')
    op.create_unique_constraint(
        'unq_job_provider', 'job', ['repository_id', 'provider', 'external_id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_job_provider', 'job', type_='unique')
    op.create_unique_constraint('unq_job_provider', 'job', ['provider', 'external_id'])
    op.drop_constraint('unq_build_provider', 'build', type_='unique')
    op.create_unique_constraint('unq_build_provider', 'build', ['provider', 'external_id'])
    # ### end Alembic commands ###
