"""remove_source_usage

Revision ID: 483a30c028ec
Revises: 133fc1714306
Create Date: 2020-01-06 15:14:05.058876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "483a30c028ec"
down_revision = "133fc1714306"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_build_source_id", table_name="build")
    op.drop_constraint("build_source_id_fkey", "build", type_="foreignkey")
    op.drop_column("build", "source_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build",
        sa.Column("source_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "build_source_id_fkey",
        "build",
        "source",
        ["source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_build_source_id", "build", ["source_id"], unique=False)
    # ### end Alembic commands ###
