"""add_build_author

Revision ID: 523842e356fa
Revises: c1d328364626
Create Date: 2018-10-01 11:57:18.018127

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "523842e356fa"
down_revision = "c1d328364626"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build", sa.Column("author_id", zeus.db.types.guid.GUID(), nullable=True)
    )
    op.create_index(
        "idx_build_author_date", "build", ["author_id", "date_created"], unique=False
    )
    op.create_index(op.f("ix_build_author_id"), "build", ["author_id"], unique=False)
    op.create_foreign_key(
        None, "build", "author", ["author_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "build", type_="foreignkey")
    op.drop_index(op.f("ix_build_author_id"), table_name="build")
    op.drop_index("idx_build_author_date", table_name="build")
    op.drop_column("build", "author_id")
    # ### end Alembic commands ###
