"""artifact_status

Revision ID: 53c5cd5b170f
Revises: 9dbc97018a55
Create Date: 2017-08-28 16:12:53.035600

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c5cd5b170f'
down_revision = '9dbc97018a55'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'artifact',
        sa.Column(
            'status',
            zeus.db.types.enum.Enum(),
            nullable=False,
            server_default=sa.text('3'),
            default=3))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'status')
    # ### end Alembic commands ###
