"""multiple_build_authors

Revision ID: 56684708bb21
Revises: 2174d4350f40
Create Date: 2020-01-07 12:56:50.563771

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56684708bb21"
down_revision = "2174d4350f40"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_author",
        sa.Column("build_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("author_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["build_id"], ["build.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("build_id", "author_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("build_author")
    # ### end Alembic commands ###
