"""author_repo

Revision ID: 579ea2c4b9e3
Revises: 255363dbe2b1
Create Date: 2017-07-08 17:48:12.623622

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '579ea2c4b9e3'
down_revision = '255363dbe2b1'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('repository_id', zeus.db.types.guid.GUID(), nullable=False))
    op.create_index(op.f('ix_author_repository_id'), 'author', ['repository_id'], unique=False)
    op.create_unique_constraint('unq_author_email', 'author', ['repository_id', 'email'])
    op.drop_constraint('author_email_key', 'author', type_='unique')
    op.create_foreign_key(
        None, 'author', 'repository', ['repository_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_unique_constraint('author_email_key', 'author', ['email'])
    op.drop_constraint('unq_author_email', 'author', type_='unique')
    op.drop_index(op.f('ix_author_repository_id'), table_name='author')
    op.drop_column('author', 'repository_id')
    # ### end Alembic commands ###
