"""build_provider

Revision ID: 5a84554d0f1f
Revises: 8fbca7496953
Create Date: 2017-07-11 12:53:46.582852

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a84554d0f1f'
down_revision = '8fbca7496953'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('build', sa.Column('provider', sa.String(), nullable=True))
    op.create_unique_constraint('unq_build_provider', 'build', ['provider', 'external_id'])
    op.add_column('job', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('job', sa.Column('provider', sa.String(), nullable=True))
    op.create_unique_constraint('unq_job_provider', 'job', ['provider', 'external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unq_job_provider', 'job', type_='unique')
    op.drop_column('job', 'provider')
    op.drop_column('job', 'external_id')
    op.drop_constraint('unq_build_provider', 'build', type_='unique')
    op.drop_column('build', 'provider')
    op.drop_column('build', 'external_id')
    # ### end Alembic commands ###
