"""options

Revision ID: 63cfa749a751
Revises: 7b7fb888f79e
Create Date: 2017-07-03 15:54:31.337609

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cfa749a751'
down_revision = '7b7fb888f79e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'itemoption',
        sa.Column('id', zeus.db.types.GUID(), nullable=False),
        sa.Column('item_id', zeus.db.types.GUID(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('item_id', 'name', name='unq_itemoption_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemoption')
    # ### end Alembic commands ###
