"""track_hooks

Revision ID: 6afba33703f5
Revises: 059fd6da96ee
Create Date: 2019-01-21 12:56:00.274097

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "6afba33703f5"
down_revision = "059fd6da96ee"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build", sa.Column("hook_id", zeus.db.types.guid.GUID(), nullable=True)
    )
    op.create_index(op.f("ix_build_hook_id"), "build", ["hook_id"], unique=False)
    op.create_foreign_key(
        None, "build", "hook", ["hook_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("hook", sa.Column("is_required", sa.Boolean(), nullable=True))
    op.add_column("job", sa.Column("hook_id", zeus.db.types.guid.GUID(), nullable=True))
    op.create_index(op.f("ix_job_hook_id"), "job", ["hook_id"], unique=False)
    op.create_foreign_key(None, "job", "hook", ["hook_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job", type_="foreignkey")
    op.drop_index(op.f("ix_job_hook_id"), table_name="job")
    op.drop_column("job", "hook_id")
    op.drop_column("hook", "is_required")
    op.drop_constraint(None, "build", type_="foreignkey")
    op.drop_index(op.f("ix_build_hook_id"), table_name="build")
    op.drop_column("build", "hook_id")
    # ### end Alembic commands ###
