"""missing_indexes

Revision ID: 6e7a43dc7b0e
Revises: 1cb2c54f3831
Create Date: 2018-03-31 15:41:16.048239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7a43dc7b0e'
down_revision = '1cb2c54f3831'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_build_date_created'), 'build', ['date_created'], unique=False)
    op.create_index(op.f('ix_repository_public'), 'repository', ['public'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_public'), table_name='repository')
    op.drop_index(op.f('ix_build_date_created'), table_name='build')
    # ### end Alembic commands ###
