"""parent_constraint

Revision ID: 723c9299360a
Revises: 7a6166862147
Create Date: 2017-07-13 13:28:04.707670

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '723c9299360a'
down_revision = '7a6166862147'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, 'patch', 'revision', ['repository_id', 'parent_revision_sha'],
        ['repository_id', 'sha']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patch', type_='foreignkey')
    # ### end Alembic commands ###
