"""Allow arbitrary artifact types

Revision ID: 83dc0a466da2
Revises: 4b3c2ca23454
Create Date: 2017-11-06 11:25:32.787482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dc0a466da2'
down_revision = '4b3c2ca23454'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'type')
    op.add_column('artifact', sa.Column(
        'type', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'type')
    op.add_column('artifact', sa.Column('type', sa.INTEGER(
    ), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
