"""add_artifact_dates

Revision ID: 87cbddd5b946
Revises: 9418cac1c4ee
Create Date: 2017-11-21 08:03:24.923077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cbddd5b946'
down_revision = '9418cac1c4ee'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'artifact',
        sa.Column(
            'date_finished',
            sa.TIMESTAMP(
                timezone=True),
            nullable=True))
    op.add_column('artifact', sa.Column('date_started', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('artifact', sa.Column('date_updated', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifact', 'date_updated')
    op.drop_column('artifact', 'date_started')
    op.drop_column('artifact', 'date_finished')
    # ### end Alembic commands ###
