"""add_webpack_stats

Revision ID: 89a8aa1c611c
Revises: 87cbddd5b946
Create Date: 2018-01-04 14:16:23.592897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import zeus

# revision identifiers, used by Alembic.
revision = "89a8aa1c611c"
down_revision = "87cbddd5b946"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webpack_asset",
        sa.Column("job_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("chunk_names", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "filename", name="unq_webpack_asset"),
    )
    op.create_index(
        op.f("ix_webpack_asset_repository_id"),
        "webpack_asset",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "webpack_entrypoint",
        sa.Column("job_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("asset_names", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "name", name="unq_webpack_entrypoint"),
    )
    op.create_index(
        op.f("ix_webpack_entrypoint_repository_id"),
        "webpack_entrypoint",
        ["repository_id"],
        unique=False,
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_webpack_entrypoint_repository_id"), table_name="webpack_entrypoint"
    )
    op.drop_table("webpack_entrypoint")
    op.drop_index(op.f("ix_webpack_asset_repository_id"), table_name="webpack_asset")
    op.drop_table("webpack_asset")


# ### end Alembic commands ###
