"""urls

Revision ID: 8bff5351578a
Revises: 1fd74fb6ef0a
Create Date: 2017-07-25 11:27:45.436698

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8bff5351578a"
down_revision = "1fd74fb6ef0a"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build", sa.Column("url", sa.String(), nullable=True))
    op.add_column("job", sa.Column("url", sa.String(), nullable=True))


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "url")
    op.drop_column("build", "url")


# ### end Alembic commands ###
