"""public_repository

Revision ID: 8e598bda7fda
Revises: 694bcef51b94
Create Date: 2018-01-20 17:29:34.783263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e598bda7fda"
down_revision = "694bcef51b94"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repository",
        sa.Column("public", sa.Boolean(), server_default="false", nullable=False),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repository", "public")


# ### end Alembic commands ###
