"""add_testcase_meta

Revision ID: 9096cdb5c97e
Revises: 495c51627ec0
Create Date: 2020-05-22 10:47:13.391860

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9096cdb5c97e"
down_revision = "495c51627ec0"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "testcase_meta",
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("hash", sa.String(length=40), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("first_build_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["first_build_id"], ["build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "hash", name="unq_testcase_meta_hash"),
    )
    op.create_index(
        op.f("ix_testcase_meta_repository_id"),
        "testcase_meta",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_testcase_meta_repository_id"), table_name="testcase_meta")
    op.drop_table("testcase_meta")
    # ### end Alembic commands ###
