"""failure_reasons

Revision ID: 9227d42a8935
Revises: 8bff5351578a
Create Date: 2017-07-25 11:46:34.702199

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9227d42a8935"
down_revision = "8bff5351578a"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failurereason",
        sa.Column("job_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("reason", zeus.db.types.enum.StrEnum(), nullable=False),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "reason", name="unq_failurereason_key"),
    )
    op.create_index(
        op.f("ix_failurereason_repository_id"),
        "failurereason",
        ["repository_id"],
        unique=False,
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_failurereason_repository_id"), table_name="failurereason")
    op.drop_table("failurereason")


# ### end Alembic commands ###
