"""hook_data

Revision ID: 9d374079e8fc
Revises: 83dc0a466da2
Create Date: 2017-11-08 15:27:00.872106

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "9d374079e8fc"
down_revision = "83dc0a466da2"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hook", sa.Column("data", zeus.db.types.json.JSONEncodedDict(), nullable=True)
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hook", "data")


# ### end Alembic commands ###
