"""repo_access

Revision ID: a1b148fec5e1
Revises: badcf9806ebd
Create Date: 2017-07-04 12:46:17.357258

"""
import zeus
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b148fec5e1'
down_revision = 'badcf9806ebd'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_access',
                    sa.Column('repository_id', zeus.db.types.GUID(), nullable=False),
                    sa.Column('user_id', zeus.db.types.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['repository_id'],
                        ['repository.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['user.id'], ), sa.PrimaryKeyConstraint('repository_id', 'user_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_access')
    # ### end Alembic commands ###
