"""build_labels

Revision ID: a456f2c3a68d
Revises: 240364a078d9
Create Date: 2017-07-14 12:19:14.873485

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a456f2c3a68d"
down_revision = "240364a078d9"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("build", sa.Column("label", sa.String(), nullable=False))
    op.add_column("job", sa.Column("label", sa.String(), nullable=True))


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "label")
    op.drop_column("build", "label")


# ### end Alembic commands ###
