"""add_testcase_date_created

Revision ID: a8bd86b031b4
Revises: 9096cdb5c97e
Create Date: 2020-05-22 10:50:17.822843

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a8bd86b031b4"
down_revision = "9096cdb5c97e"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testcase",
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testcase", "date_created")
    # ### end Alembic commands ###
