"""cover_test_history

Revision ID: af3f4bdc27d1
Revises: 33da83c61635
Create Date: 2019-01-23 12:53:55.396720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af3f4bdc27d1"
down_revision = "33da83c61635"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_testcase_repo_hash",
        "testcase",
        ["repository_id", "hash", "result"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_testcase_repo_hash", table_name="testcase")
    # ### end Alembic commands ###
