"""User and repository tokens

Revision ID: b3eb342cfd7e
Revises: 83dc0a466da2
Create Date: 2017-11-08 15:33:52.810846

"""
import zeus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3eb342cfd7e"
down_revision = "83dc0a466da2"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_api_token",
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("repository_id"),
    )
    op.create_table(
        "user_api_token",
        sa.Column("user_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("user_id"),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_api_token")
    op.drop_table("repository_api_token")


# ### end Alembic commands ###
