"""non_null_fields

Revision ID: b605b5627d91
Revises: 0f352d0c7de2
Create Date: 2017-07-11 13:18:21.185510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b605b5627d91'
down_revision = '0f352d0c7de2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'api_token', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column('filecoverage', 'data', existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        'filecoverage', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        'filecoverage', 'diff_lines_covered', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'filecoverage', 'diff_lines_uncovered', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column('filecoverage', 'lines_covered', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('filecoverage', 'lines_uncovered', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('identity', 'config', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        'identity', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        'revision', 'date_committed', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        'revision', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column('user', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column('revision', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column(
        'revision', 'date_committed', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column('identity', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column('identity', 'config', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('filecoverage', 'lines_uncovered', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('filecoverage', 'lines_covered', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'filecoverage', 'diff_lines_uncovered', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column('filecoverage', 'diff_lines_covered', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'filecoverage', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column('filecoverage', 'data', existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        'api_token', 'date_created', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
