"""remove_bundles

Revision ID: bc3f73aeee99
Revises: 0e26830acd30
Create Date: 2018-01-05 15:18:18.486227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc3f73aeee99"
down_revision = "0e26830acd30"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bundle_entrypoint_asset")
    op.drop_table("bundle_asset")
    op.drop_table("bundle_entrypoint")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bundle_entrypoint",
        sa.Column("job_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "repository_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name="bundle_entrypoint_job_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name="bundle_entrypoint_repository_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="bundle_entrypoint_pkey"),
        sa.UniqueConstraint("job_id", "name", name="unq_bundle_entrypoint"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "bundle_entrypoint_asset",
        sa.Column(
            "entrypoint_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("asset_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["bundle_asset.id"],
            name="bundle_entrypoint_asset_asset_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["entrypoint_id"],
            ["bundle_entrypoint.id"],
            name="bundle_entrypoint_asset_entrypoint_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "entrypoint_id", "asset_id", name="bundle_entrypoint_asset_pkey"
        ),
    )
    op.create_table(
        "bundle_asset",
        sa.Column("job_id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "chunk_names",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "repository_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "date_created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name="bundle_asset_job_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name="bundle_asset_repository_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="bundle_asset_pkey"),
        sa.UniqueConstraint("job_id", "name", name="unq_bundle_asset"),
    )


# ### end Alembic commands ###
