"""email_verified

Revision ID: c257bd5a6236
Revises: f810bb64d19b
Create Date: 2017-10-07 14:16:25.952757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c257bd5a6236'
down_revision = 'f810bb64d19b'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email', 'verified',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###
