"""remove_unused_index

Revision ID: cd1324dcb6ba
Revises: de49ae79ce38
Create Date: 2019-01-23 12:44:47.439101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd1324dcb6ba"
down_revision = "de49ae79ce38"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_build_author_id", table_name="build")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_build_author_id", "build", ["author_id"], unique=False)
    # ### end Alembic commands ###
