"""add_testcase_rollup

Revision ID: d05e8a773f11
Revises: 392eb568af84
Create Date: 2020-05-21 09:21:09.410709

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "d05e8a773f11"
down_revision = "392eb568af84"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "testcase_rollup",
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("hash", sa.String(length=40), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("total_duration", sa.Integer(), nullable=False),
        sa.Column("runs_failed", sa.Integer(), nullable=False),
        sa.Column("runs_passed", sa.Integer(), nullable=False),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "repository_id", "hash", "date", name="unq_testcase_rollup_hash"
        ),
    )
    op.create_index(
        op.f("ix_testcase_rollup_repository_id"),
        "testcase_rollup",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_testcase_rollup_repository_id"), table_name="testcase_rollup"
    )
    op.drop_table("testcase_rollup")
    # ### end Alembic commands ###
