"""refactor_bundles

Revision ID: d84e557ec8f6
Revises: bc3f73aeee99
Create Date: 2018-01-05 15:20:06.706670

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "d84e557ec8f6"
down_revision = "bc3f73aeee99"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bundle",
        sa.Column("job_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "name", name="unq_bundle"),
    )
    op.create_index(
        op.f("ix_bundle_repository_id"), "bundle", ["repository_id"], unique=False
    )
    op.create_table(
        "bundle_asset",
        sa.Column("bundle_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("job_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bundle_id"], ["bundle.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bundle_id", "name", name="unq_bundle_asset"),
    )
    op.create_index(
        op.f("ix_bundle_asset_repository_id"),
        "bundle_asset",
        ["repository_id"],
        unique=False,
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bundle_asset_repository_id"), table_name="bundle_asset")
    op.drop_table("bundle_asset")
    op.drop_index(op.f("ix_bundle_repository_id"), table_name="bundle")
    op.drop_table("bundle")


# ### end Alembic commands ###
