"""bundle_job_id_indexes

Revision ID: de49ae79ce38
Revises: 404ac069de83
Create Date: 2019-01-22 12:58:06.135756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de49ae79ce38"
down_revision = "404ac069de83"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_bundle_job_id"), "bundle", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_bundle_asset_job_id"), "bundle_asset", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bundle_asset_job_id"), table_name="bundle_asset")
    op.drop_index(op.f("ix_bundle_job_id"), table_name="bundle")
    # ### end Alembic commands ###
