"""add_repo_tree

Revision ID: ee27858bf719
Revises: c1d328364626
Create Date: 2018-07-23 22:18:14.836067

"""
from alembic import op
import sqlalchemy as sa
import zeus


# revision identifiers, used by Alembic.
revision = "ee27858bf719"
down_revision = "c1d328364626"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_ref",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column(
            "date_created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "name", name="unq_repository_ref"),
    )
    op.create_index(
        op.f("ix_repository_ref_repository_id"),
        "repository_ref",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "repository_tree",
        sa.Column("ref_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("revision_sha", sa.String(length=40), nullable=True),
        sa.Column("repository_id", zeus.db.types.guid.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["ref_id"], ["repository_ref.id"]),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["revision_sha"], ["revision.sha"]),
        sa.PrimaryKeyConstraint("ref_id", "order"),
        sa.UniqueConstraint("ref_id", "revision_sha", name="unq_tree_revision"),
    )
    op.create_index(
        op.f("ix_repository_tree_repository_id"),
        "repository_tree",
        ["repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_repository_tree_repository_id"), table_name="repository_tree"
    )
    op.drop_table("repository_tree")
    op.drop_index(op.f("ix_repository_ref_repository_id"), table_name="repository_ref")
    op.drop_table("repository_ref")
    # ### end Alembic commands ###
