"""repo_updates

Revision ID: f58f6920c79d
Revises: 63cfa749a751
Create Date: 2017-07-03 16:43:57.258560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58f6920c79d'
down_revision = '63cfa749a751'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('repository', sa.Column('last_update_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'last_update_attempt')
    op.drop_column('repository', 'last_update')
    # ### end Alembic commands ###
