#!/bin/bash -eu

# PROJECT_ID="$(gcloud config get-value project)"

PROJECT_ID="zeus-176020"

IMAGE="gcr.io/${PROJECT_ID}/zeus"

REF=${1:-"origin/master"}

function update_repo() {
    mkdir -p dist
    cd dist

    if [[ -e zeus/.git ]]; then
        echo "> Updating source repository"
        cd zeus
        git fetch -a
    else
        echo "> Cloning source repository"
        git clone git@github.com:getsentry/zeus.git
        cd zeus
    fi

    git reset $REF --hard
    git clean -fdx
    cd ../..
}

function bind_version() {
    cd dist/zeus
    VERSION=$(git rev-parse head)
    cd ../..
}
