#!/bin/bash -eux

# https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md

export LC_ALL=C

export APP_INSTANCE_NAME=rabbitmq-1
export NAMESPACE=default

export REPLICAS=1

export TAG="3.7"

export RABBITMQ_DEFAULT_USER=rabbit
export RABBITMQ_DEFAULT_PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 12 | head -n 1 | tr -d '\n' | base64)
export RABBITMQ_ERLANG_COOKIE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | tr -d '\n' | base64)

export METRICS_EXPORTER_ENABLED=true

export IMAGE_RABBITMQ=marketplace.gcr.io/google/rabbitmq
export IMAGE_RABBITMQ_INIT=marketplace.gcr.io/google/rabbitmq/debian9:${TAG}
export IMAGE_METRICS_EXPORTER="marketplace.gcr.io/google/rabbitmq/prometheus-to-sd:${TAG}"

export RABBITMQ_SERVICE_ACCOUNT=$APP_INSTANCE_NAME-rabbitmq-sa

envsubst '$APP_INSTANCE_NAME' < scripts/rbac.yaml > "${APP_INSTANCE_NAME}_rbac.yaml"

helm template \
  "$APP_INSTANCE_NAME" \
  "chart/rabbitmq" \
  --namespace "$NAMESPACE" \
  --set rabbitmq.image.repo="$IMAGE_RABBITMQ" \
  --set rabbitmq.image.tag="$TAG" \
  --set rabbitmq.initImage="$IMAGE_RABBITMQ_INIT" \
  --set rabbitmq.replicas="$REPLICAS" \
  --set rabbitmq.erlangCookie="$RABBITMQ_ERLANG_COOKIE" \
  --set rabbitmq.user="$RABBITMQ_DEFAULT_USER" \
  --set rabbitmq.password="$RABBITMQ_DEFAULT_PASS" \
  --set rabbitmq.serviceAccount="$RABBITMQ_SERVICE_ACCOUNT" \
  --set metrics.image="$IMAGE_METRICS_EXPORTER" \
  --set metrics.exporter.enabled="$METRICS_EXPORTER_ENABLED" \
  > "${APP_INSTANCE_NAME}_manifest.yaml"

# echo "https://console.cloud.google.com/kubernetes/application/${ZONE}/${CLUSTER}/${NAMESPACE}/${APP_INSTANCE_NAME}"
