export const SET_CURRENT_AUTH = 'SET_CURRENT_AUTH';

export const ADD_INDICATOR = 'ADD_INDICATOR',
  REMOVE_INDICATOR = 'REMOVE_INDICATOR';

export const ADD_REPO = 'ADD_REPO',
  LOAD_REPO_LIST = 'LOAD_REPO_LIST',
  REMOVE_REPO = 'REMOVE_REPO',
  UPDATE_REPO = 'UPDATE_REPO';

export const ADD_BUILD = 'ADD_BUILD',
  LOAD_BUILD_LIST = 'LOAD_BUILD_LIST',
  PRE_LOAD_BUILD_LIST = 'PRE_LOAD_BUILD_LIST',
  REMOVE_BUILD = 'REMOVE_BUILD',
  UPDATE_BUILD = 'UPDATE_BUILD';

export const LOAD_CHANGE_REQUEST_LIST = 'LOAD_CHANGE_REQUEST_LIST',
  PRE_LOAD_CHANGE_REQUEST_LIST = 'PRE_LOAD_CHANGE_REQUEST_LIST';

export const STREAM_CONNECT = 'STREAM:CONNECT',
  STREAM_DISCONNECT = 'STREAM:DISCONNECT',
  STREAM_OPEN = 'STREAM:OPEN',
  STREAM_ERROR = 'STREAM:ERROR',
  STREAM_MESSAGE = 'STREAM:MESSAGE',
  STREAM_SUBSCRIBE = 'STREAM:SUBSCRIBE',
  STREAM_UNSUBSCRIBE = 'STREAM:UNSUBSCRIBE';

export const ADD_REVISION = 'ADD_REVISION',
  LOAD_REVISION_LIST = 'LOAD_REVISION_LIST',
  PRE_LOAD_REVISION_LIST = 'PRE_LOAD_REVISION_LIST',
  REMOVE_REVISION = 'REMOVE_REVISION',
  UPDATE_REVISION = 'UPDATE_REVISION';
